const cards = [
  {
    id: 1,
    title: 'React',
    image: './assets/react-logo.png',
    alt: 'React',
    description: 'A JavaScript library for building user interfaces',
    href: 'https://reactjs.org/',
    link: 'React docs',
  },
  {
    id: 2,
    title: 'Angular',
    image: './assets/angular.png',
    alt: 'Angular',
    description: 'The modern web developers platform',
    href: 'https://angularjs.org/',
    link: 'Angular docs',
  },
  {
    id: 3,
    title: 'Vue',
    image: './assets/vue.png',
    alt: 'Vue',
    description: 'The progressive JavaScript framework',
    href: 'https://v3.vuejs.org/',
    link: 'Vue docs',
  },
  {
    id: 4,
    title: 'Svelte',
    image: './assets/svelte.png',
    alt: 'Svelte',
    description: 'Cybernetically enhanced Web Applications',
    href: 'https://ru.svelte.dev/',
    link: 'Svelte docs',
  },
  {
    id: 5,
    title: 'Ember',
    image: './assets/ember.png',
    alt: 'Ember',
    description: 'A framework for ambitious web developers.',
    href: 'https://emberjs.com/',
    link: 'Ember docs',
  },
  {
    id: 6,
    title: 'Backbone',
    image: './assets/backbone.png',
    alt: 'Backbone',
    description: 'Backbone.js gives structure to web applications',
    href: 'https://backbonejs.org/',
    link: 'Backbone docs',
  },
  {
    id: 7,
    title: 'Preact',
    image: './assets/preact.png',
    alt: 'Preact',
    description: 'Fast 3kB alternative to React with the same modern API',
    href: 'https://preactjs.com/',
    link: 'Preact docs',
  },
  {
    id: 8,
    title: 'Other or none js',
    image: './assets/none-fw.png',
    alt: 'Other or none js',
    description: 'Vanilla JS',
    href: 'https://www.javascript.com/',
    link: 'JS ->',
  },
];

export default cards;
